# Generated by Django 3.2.7 on 2022-03-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='batch',
        ),
    ]
